#!/usr/bin/env bash

echo "Initiating startup sequence for HornyBot."

echo "Terminating any existing instances..."
pkill -f "hornybot"

rm nohup.out

echo "Checking for API keys..."

KEY_DIR="keys"
KEYS="discord-key google-key search-id"

for key in $KEYS;
do
	if test -f "$KEY_DIR/$key"; 
	then
		echo "$KEY_DIR/$key found. Proceeding."
	else
		echo "$KEY_DIR/$key not found. Exiting."
		exit
	fi
done

echo "Launching the bot..."

# Using nohup.out as somewhat of a logfile for now.
nohup python3 HornyBot/hornybot.py > /dev/null 2>&1 & 
